// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABXoV8K_IyksqibU0DugIEWn4v4xR9XAk',
    appId: '1:925394531708:web:95c140cbc43acb33c620f9',
    messagingSenderId: '925394531708',
    projectId: 'med-g-450d2',
    authDomain: 'med-g-450d2.firebaseapp.com',
    storageBucket: 'med-g-450d2.appspot.com',
    measurementId: 'G-G9HGYDLENV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy_hYpBRnIcD2z8WR6FNeHKZfhHvW9UIw',
    appId: '1:925394531708:android:d9c7cefd931b4c26c620f9',
    messagingSenderId: '925394531708',
    projectId: 'med-g-450d2',
    storageBucket: 'med-g-450d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEAl6KA0wyItEos3uwlLnBX0wF-JePPEQ',
    appId: '1:925394531708:ios:73be636b5684847dc620f9',
    messagingSenderId: '925394531708',
    projectId: 'med-g-450d2',
    storageBucket: 'med-g-450d2.appspot.com',
    iosBundleId: 'com.example.medg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEAl6KA0wyItEos3uwlLnBX0wF-JePPEQ',
    appId: '1:925394531708:ios:83dac3c99be6d3fec620f9',
    messagingSenderId: '925394531708',
    projectId: 'med-g-450d2',
    storageBucket: 'med-g-450d2.appspot.com',
    iosBundleId: 'com.example.medg.RunnerTests',
  );
}
